# Generated by Django 2.1.1 on 2018-09-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canalero', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='Reparto',
        ),
        migrations.AddField(
            model_name='orden',
            name='Reparto',
            field=models.ManyToManyField(to='canalero.Reparto'),
        ),
        migrations.DeleteModel(
            name='Reparto',
        ),
    ]
