# Generated by Django 2.1.1 on 2018-10-11 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_parcela'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='Reparto',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='Usuario',
        ),
        migrations.RemoveField(
            model_name='parcela',
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
        migrations.DeleteModel(
            name='Parcela',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
