# Generated by Django 2.1.1 on 2018-09-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reparto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=50)),
                ('Numero', models.PositiveSmallIntegerField()),
                ('FechaReparto', models.DateField()),
                ('Estado', models.BooleanField(default=True)),
            ],
        ),
    ]
