# Generated by Django 2.1.1 on 2018-10-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('idacceso', models.IntegerField(db_column='idAcceso', primary_key=True, serialize=False)),
                ('desccripcion', models.CharField(db_column='Desccripcion', max_length=45)),
            ],
            options={
                'db_table': 'acceso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asamblea',
            fields=[
                ('idasamblea', models.AutoField(db_column='idAsamblea', primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha_registro', models.DateTimeField()),
                ('fecha_asamblea', models.DateTimeField()),
            ],
            options={
                'db_table': 'asamblea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('idasistencia', models.AutoField(db_column='idAsistencia', primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=45)),
                ('hora', models.DateTimeField()),
            ],
            options={
                'db_table': 'asistencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('idcanal', models.AutoField(db_column='idCanal', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('tamano', models.FloatField(blank=True, null=True)),
                ('ubucacion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'canal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Caudal',
            fields=[
                ('idcaudal', models.AutoField(db_column='idCaudal', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('nivel', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'caudal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('idcomite', models.AutoField(db_column='idComite', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_registro', models.DateTimeField()),
                ('estado', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'comite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('idcomprobante', models.AutoField(db_column='idComprobante', primary_key=True, serialize=False)),
                ('ticket', models.IntegerField()),
                ('concepto', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=45)),
                ('monto', models.FloatField()),
            ],
            options={
                'db_table': 'comprobante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Destajo',
            fields=[
                ('iddestajo', models.AutoField(db_column='idDestajo', primary_key=True, serialize=False)),
                ('tamano_matros', models.FloatField()),
                ('num_orden', models.IntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'destajo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetLimpieza',
            fields=[
                ('iddet_limpieza', models.AutoField(db_column='idDet_limpieza', primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=10)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'det_limpieza',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetLista',
            fields=[
                ('iddet_lista', models.AutoField(db_column='idDet_Lista', primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'det_lista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('iddireccion', models.AutoField(db_column='idDireccion', primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=20)),
                ('cod_postal', models.IntegerField(blank=True, null=True)),
                ('departamento', models.CharField(blank=True, max_length=20, null=True)),
                ('provinciaa', models.CharField(blank=True, max_length=20, null=True)),
                ('distrito', models.CharField(blank=True, max_length=20, null=True)),
                ('dir_larga', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'direccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Limpieza',
            fields=[
                ('idlimpieza', models.AutoField(db_column='idLimpieza', primary_key=True, serialize=False)),
                ('decripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('tipo', models.CharField(max_length=20)),
                ('fecha_registro', models.DateField()),
                ('fecha_limpieza', models.DateField()),
                ('fecha_revision', models.DateTimeField()),
            ],
            options={
                'db_table': 'limpieza',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('idlista', models.AutoField(db_column='idLista', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('foto', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('idmulta', models.AutoField(db_column='idMulta', primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'multa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('idnoticia', models.AutoField(db_column='idNoticia', primary_key=True, serialize=False)),
                ('titular', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=100)),
                ('fechahora', models.DateTimeField(db_column='fechaHora')),
                ('foto', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'noticia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('idobra', models.AutoField(db_column='idObra', primary_key=True, serialize=False)),
                ('decripcion', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('monto', models.FloatField()),
                ('foto', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'obra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenRiego',
            fields=[
                ('idorden_riego', models.AutoField(db_column='idOrden_riego', primary_key=True, serialize=False)),
                ('ticket', models.IntegerField(blank=True, null=True)),
                ('fecha_establecida', models.DateTimeField()),
                ('decha_inicio', models.DateTimeField(blank=True, null=True)),
                ('duracion', models.FloatField()),
                ('hectareas', models.FloatField()),
                ('tipo_duracion', models.CharField(blank=True, max_length=10, null=True)),
                ('importe', models.FloatField()),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'orden_riego',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('idparcela', models.AutoField(db_column='idParcela', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('ubicacion', models.CharField(max_length=45)),
                ('num_toma', models.IntegerField()),
                ('hectareas', models.FloatField()),
                ('has_sembradas', models.FloatField()),
                ('planos', models.TextField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'parcela',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idpersona', models.AutoField(db_column='idPersona', primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=8)),
                ('ap_paterno', models.CharField(max_length=30)),
                ('ap_materno', models.CharField(max_length=30)),
                ('nombres', models.CharField(max_length=35)),
                ('alias', models.CharField(blank=True, max_length=20, null=True)),
                ('sexo', models.CharField(max_length=1)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=13, null=True)),
                ('foto', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reparto',
            fields=[
                ('idreparto', models.AutoField(db_column='idReparto', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('tipo', models.CharField(max_length=10)),
                ('repartocol', models.CharField(blank=True, db_column='Repartocol', max_length=45, null=True)),
                ('fecha_registro', models.DateField()),
                ('fecha_reparto', models.DateTimeField()),
            ],
            options={
                'db_table': 'reparto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Talonario',
            fields=[
                ('idtalonario', models.AutoField(db_column='idTalonario', primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('primer_ticket', models.IntegerField()),
                ('cantida_tickets', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'talonario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=45)),
                ('pass_user', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
