# Generated by Django 2.1.1 on 2018-10-17 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_agendaasamblea_archivosparcela_authgroup_authgrouppermissions_authpermission_authuser_authusergroups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={'managed': False, 'permissions': (('es_presidente', 'Es Presidente'), ('es_canalero', 'Es Canalero'))},
        ),
    ]
