# Generated by Django 2.1.1 on 2018-10-17 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_auto_20181017_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={'managed': False, 'permissions': (('es_presidente', 'Presidente'), ('es_canalero', 'Canalero'), ('es_tesorero', 'Tesorero'), ('es_vocal', 'Vocal'), ('es_usuario', 'Usuario'))},
        ),
    ]
