# Generated by Django 2.2.3 on 2019-07-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_compmulta_comporden_multaasistencia_multalimpia_multaorden'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetAsambCanal',
            fields=[
                ('id_dt_asmb_canal', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'det_asamb_canal',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Acceso',
        ),
        migrations.DeleteModel(
            name='Asistencia',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
