# Generated by Django 2.2.3 on 2019-09-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_auto_20190728_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultaOrden1',
            fields=[
                ('id_multa_orden', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'multa_orden1',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='MultaOrden',
        ),
    ]
