# Generated by Django 2.2.3 on 2019-09-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_auto_20190905_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultaOrden',
            fields=[
                ('id_multa_orden', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'multa_orden',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='MultaOrden1',
        ),
    ]
